# Generated by Django 4.2 on 2023-12-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
