# Generated by Django 4.2 on 2023-12-27 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientesApp', '0002_cliente_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='file_path',
        ),
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_content', models.ImageField(blank=True, null=True, upload_to='')),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientesApp.cliente')),
            ],
        ),
    ]
