# Generated by Django 4.2 on 2023-12-27 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientesApp', '0003_remove_cliente_file_path_archivos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Archivos',
            new_name='Archivo',
        ),
    ]
