# Generated by Django 4.2 on 2023-12-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientesApp', '0005_rename_news_archivo_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivo',
            options={'verbose_name': 'archivo'},
        ),
        migrations.AlterField(
            model_name='archivo',
            name='image_content',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
