# Generated by Django 4.2 on 2023-12-29 18:33

import clientesApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientesApp', '0006_alter_archivo_options_alter_archivo_image_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='image_content',
            field=models.FileField(blank=True, null=True, upload_to=clientesApp.models.user_directory_path),
        ),
    ]
