# Generated by Django 4.2 on 2024-01-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientesApp', '0007_alter_archivo_image_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoServicio', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='servicio',
        ),
        migrations.AddField(
            model_name='cliente',
            name='servicio',
            field=models.ManyToManyField(to='clientesApp.servicio'),
        ),
    ]
