# Generated by Django 4.2 on 2024-01-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientesApp', '0008_servicio_remove_cliente_servicio_cliente_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='tipoServicio',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
