# Generated by Django 4.2 on 2024-01-12 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientesApp', '0009_alter_servicio_tiposervicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='servicio',
            new_name='servicios',
        ),
    ]
