# Generated by Django 4.2 on 2024-01-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientesApp', '0010_rename_servicio_cliente_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='desistido',
            field=models.BooleanField(default=False),
        ),
    ]
