# Generated by Django 4.2 on 2024-01-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientesApp', '0011_cliente_desistido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
